- number: <a href="/services/linkedin-makeover">Linkedin & Resume Makeover</a>
  name:
  description: We will optimize your Resume & LinkedIn with our expert review & rewrite services.

- number: <a href="/tech">Coaching Sessions</a>
  name:
  description: Our coaches will work with you on detailed, tailored sessions to get you ready for any challenge.

- number: <a href="mailto:hello@techinterview.coach">Negotiation Support</a>
  name:
  description: We will be by your side to review your contract & negotiate the salary you deserve.
